%% The E2E seal scheme 1 vectors (test/vectors/E2E_SEAL_V1.md), generated by
%% an independent Rust implementation (scripts/e2e_seal_vectors), reproduced
%% byte for byte by `macula_seal' on OTP `crypto'. Every intermediate value is
%% checked, so a mismatch names the step that differs.
-module(macula_seal_vectors_tests).

-include_lib("eunit/include/eunit.hrl").

vectors_test_() ->
    Doc = vectors(),
    Recipients = maps:get(<<"recipients">>, Doc),
    [{"scheme 1", ?_assertEqual(1, maps:get(<<"scheme">>, Doc))}]
    ++ [{recipient_name(Profile), fun() -> recipient_checked(binary_to_existing_atom(Profile), R) end}
        || Profile := R <- Recipients]
    ++ [{call_name(C), fun() -> call_checked(C, maps:get(maps:get(<<"profile">>, C), Recipients)) end}
        || C <- maps:get(<<"calls">>, Doc)]
    ++ [{"event", fun() -> event_checked(E) end} || E <- maps:get(<<"events">>, Doc)]
    ++ [{"refusal: " ++ binary_to_list(maps:get(<<"why">>, R)), fun() -> refusal_checked(R) end}
        || R <- maps:get(<<"refusals">>, Doc)].

refusal_checked(R) ->
    Private = #{mlkem_dk => x(R, <<"mlkem_dk">>), p384_priv => x(R, <<"p384_priv">>)},
    ?assertEqual({error, sealed_refused},
                 macula_seal:recipient_secret(pq_hybrid, Private, x(R, <<"key_as_carried">>), x(R, <<"kem_ct">>))).

%% A recipient's key as carried, its hash and its id.
recipient_checked(Profile, R) ->
    ?assertEqual(x(R, <<"key_as_carried">>), macula_seal:key_as_carried(recipient_public(Profile, R))),
    ?assertEqual(x(R, <<"key_hash">>), macula_seal:key_hash(x(R, <<"key_as_carried">>))),
    ?assertEqual(x(R, <<"key_id">>), macula_seal:key_id(x(R, <<"key_as_carried">>))).

call_checked(C, R) ->
    Profile = profile(C),
    Private = recipient_private(Profile, R),
    %% The recipient's side: decapsulation, the combiner, the keys.
    ?assertEqual({ok, x(C, <<"ss">>)},
                 macula_seal:recipient_secret(Profile, Private, x(R, <<"key_as_carried">>), x(C, <<"kem_ct">>))),
    FrameType = maps:get(<<"frame_type">>, C),
    Parties = {x(C, <<"request_id">>), x(C, <<"caller">>), x(C, <<"target">>)},
    ?assertEqual({x(C, <<"k_req">>), x(C, <<"k_rep">>)}, macula_seal:call_keys(x(C, <<"ss">>), FrameType, Parties)),
    Request = #{frame_type => FrameType, realm => x(C, <<"realm">>), procedure => maps:get(<<"procedure">>, C),
                caller => x(C, <<"caller">>), target => x(C, <<"target">>), request_id => x(C, <<"request_id">>),
                deadline => maps:get(<<"deadline">>, C)},
    Req = maps:get(<<"request">>, C),
    ?assertEqual(x(Req, <<"aad">>), macula_seal:request_aad(Request)),
    sealed_both_ways(x(C, <<"k_req">>), Req),
    reply_checked(FrameType, C, Request),
    streams_checked(FrameType, C, Parties).

%% A call's reply; a STREAM_OPEN is answered by stream frames, never a reply.
reply_checked(<<"call">>, C, Request) ->
    Rep = maps:get(<<"reply">>, C),
    ?assertEqual(x(Rep, <<"aad">>), macula_seal:reply_aad(Request, maps:get(<<"frame_type">>, Rep),
                                                          x(Rep, <<"request_hash">>), x(Rep, <<"responded_by">>))),
    sealed_both_ways(x(C, <<"k_rep">>), Rep);
reply_checked(<<"stream_open">>, C, _Request) ->
    ?assertNot(maps:is_key(<<"reply">>, C)).

streams_checked(<<"stream_open">>, C, Parties) ->
    ?assertEqual({x(C, <<"k_c2p">>), x(C, <<"k_p2c">>)}, macula_seal:stream_keys(x(C, <<"ss">>), Parties)),
    [begin
         Dir = maps:get(<<"direction">>, F),
         Seq = maps:get(<<"seq">>, F),
         ?assertEqual(x(F, <<"aad">>),
                      macula_seal:stream_aad(maps:get(<<"frame_type">>, F), x(C, <<"request_id">>), Seq, Dir)),
         caller_nonce_derived(Dir, Seq, F),
         sealed_both_ways(x(C, direction_key(Dir)), F)
     end || F <- maps:get(<<"frames">>, C)];
streams_checked(<<"call">>, _C, _Parties) ->
    ok.

caller_nonce_derived(0, Seq, F) -> ?assertEqual(x(F, <<"nonce">>), macula_seal:stream_nonce(Seq));
caller_nonce_derived(1, _Seq, _F) -> ok.

direction_key(0) -> <<"k_c2p">>;
direction_key(1) -> <<"k_p2c">>.

event_checked(E) ->
    ?assertEqual(x(E, <<"k_pub">>), macula_seal:event_key(x(E, <<"k_g">>), x(E, <<"publisher">>))),
    ?assertEqual(x(E, <<"aad">>), macula_seal:event_aad(x(E, <<"realm">>), maps:get(<<"topic">>, E),
                                                        x(E, <<"publisher">>), maps:get(<<"seq">>, E),
                                                        maps:get(<<"published_at">>, E))),
    sealed_both_ways(x(E, <<"k_pub">>), E).

%% The ciphertext the vector gives, and back: a flipped bit anywhere refuses.
sealed_both_ways(Key, V) ->
    [Nonce, Aad, Plain, Ct] = [x(V, K) || K <- [<<"nonce">>, <<"aad">>, <<"plain">>, <<"ct">>]],
    ?assertEqual(Ct, macula_seal:seal(Key, Nonce, Aad, Plain)),
    ?assertEqual({ok, Plain}, macula_seal:open(Key, Nonce, Aad, Ct)),
    ?assertEqual({error, sealed_refused}, macula_seal:open(Key, Nonce, <<Aad/binary, 0>>, Ct)),
    ?assertEqual({error, sealed_refused}, macula_seal:open(Key, Nonce, Aad, flipped(Ct))).

%%%===================================================================
%%% Helpers
%%%===================================================================

vectors() ->
    {ok, Bytes} = file:read_file(vector_file()),
    json:decode(Bytes).

%% The source tree's vector file, from the project root eunit runs in, or
%% from the build tree's copy of the application.
vector_file() ->
    first_existing(["test/vectors/e2e_seal_v1.json", "../../test/vectors/e2e_seal_v1.json"]
                   ++ [filename:join([Dir, "..", "..", "..", "..", "test", "vectors", "e2e_seal_v1.json"])
                       || Dir <- [code:lib_dir(macula)], is_list(Dir)]).

first_existing([F | Rest]) ->
    case filelib:is_regular(F) of
        true -> F;
        false -> first_existing(Rest)
    end.

x(Map, Key) -> binary:decode_hex(maps:get(Key, Map)).

profile(C) -> binary_to_existing_atom(maps:get(<<"profile">>, C)).

recipient_public(pq_pure, R) -> #{mlkem_ek => x(R, <<"mlkem_ek">>)};
recipient_public(pq_hybrid, R) -> #{mlkem_ek => x(R, <<"mlkem_ek">>), p384_pub => x(R, <<"p384_pub">>)}.

recipient_private(pq_pure, R) -> #{mlkem_dk => x(R, <<"mlkem_dk">>)};
recipient_private(pq_hybrid, R) -> #{mlkem_dk => x(R, <<"mlkem_dk">>), p384_priv => x(R, <<"p384_priv">>)}.

recipient_name(Profile) -> binary_to_list(<<"recipient ", Profile/binary>>).

call_name(C) -> binary_to_list(<<(maps:get(<<"profile">>, C))/binary, " ", (maps:get(<<"frame_type">>, C))/binary>>).

flipped(<<First, Rest/binary>>) -> <<(First bxor 1), Rest/binary>>.
