#!/bin/bash
set -e

# Macula QUIC Distribution Test - Entrypoint
#
# This script configures and starts a test node using QUIC distribution.
# QUIC distribution uses port@ip naming convention.

echo "==================================================="
echo "  Macula QUIC Distribution Test Node"
echo "==================================================="

# Get configuration from environment
NODE_NAME="${NODE_NAME:-node}"
NODE_IP="${NODE_IP:-127.0.0.1}"
MACULA_DIST_PORT="${MACULA_DIST_PORT:-4433}"
ERLANG_COOKIE="${ERLANG_COOKIE:-macula_dist_test_cookie}"

# QUIC distribution uses port@ip naming convention
FULL_NODE_NAME="${MACULA_DIST_PORT}@${NODE_IP}"

echo "  Node Name:    ${FULL_NODE_NAME}"
echo "  Protocol:     QUIC (macula_dist)"
echo "  QUIC Port:    ${MACULA_DIST_PORT}"
echo "  Health Port:  ${HEALTH_PORT:-9100}"
echo "  Cookie:       ${ERLANG_COOKIE}"
echo "  Bootstrap:    ${BOOTSTRAP_NODES:-none}"
echo "==================================================="

# Ensure certs directory exists and has proper certs
CERT_DIR="/opt/app/certs"
if [ ! -f "${CERT_DIR}/cert.pem" ] || [ ! -f "${CERT_DIR}/key.pem" ]; then
    echo "Generating TLS certificates..."
    mkdir -p "${CERT_DIR}"
    openssl req -x509 -newkey rsa:2048 \
        -keyout "${CERT_DIR}/key.pem" \
        -out "${CERT_DIR}/cert.pem" \
        -days 365 -nodes \
        -subj '/CN=macula-dist-test' 2>/dev/null
fi

# Write vm.args with QUIC distribution configuration
cat > /opt/app/releases/0.1.0/vm.args << VMARGS
## Macula QUIC Distribution Test Node
## Generated by entrypoint.sh

## Node name (port@ip format for QUIC distribution)
-name ${FULL_NODE_NAME}
-setcookie ${ERLANG_COOKIE}

## QUIC distribution - replaces EPMD + TCP
-proto_dist macula
-no_epmd
-start_epmd false

## Certificate directory for QUIC TLS
-kernel macula_dist_cert_dir '"/opt/app/certs"'

## Kernel settings
+K true
+A 32
VMARGS

echo "vm.args written to /opt/app/releases/0.1.0/vm.args"

# Export for the application to use
export NODE_NAME
export NODE_IP
export MACULA_DIST_PORT
export ERLANG_COOKIE
export BOOTSTRAP_NODES

# Start the release
echo "Starting Erlang node with QUIC distribution..."
exec /opt/app/bin/macula_dist_test foreground
